In [17]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
#Import the dataset
fn=r'feb23_out.xlsx'
reported=pd.read_excel(fn)
bn=r'Baseline_2020.xlsx'
baseline=pd.read_excel(bn)

In [18]:
#What if all we care about is GPCD?
#Limit the dataset to the months we're interested in 
reported_drought=reported[reported['Reporting Month']>pd.to_datetime('2021-07-01',format='%Y-%m-%d')]
rsub=reported_drought[['Supplier Name','Reporting Month','Total Population Served','Hydrologic Region','CALCULATED Total Potable Water Production Gallons (Ag Excluded)']]
rsub.loc[:,'Month']=rsub['Reporting Month'].dt.month
#Join the baseline values
rmerge=pd.merge(rsub.rename(columns={'CALCULATED Total Potable Water Production Gallons (Ag Excluded)':'Current'}),
baseline[['Supplier Name','Month','Total Potable Production minus ag, gallons']].rename(columns={'Total Potable Production minus ag, gallons':'Baseline'}))
#What was the median population for 2020?
r20=reported[reported['Reporting Month'].dt.year==2020]
x=0
pstore=pd.DataFrame()
for s in r20['Supplier Name'].unique():
    r20s=r20[r20['Supplier Name']==s]
    pstore.loc[x,'Supplier Name']=s
    pstore.loc[x,'Baseline Population']=r20s['Total Population Served'].median()
    x+=1
#Thermalito was added after 2020
pstore.loc[x,'Supplier Name']='Thermalito Water and Sewer District'
pstore.loc[x,'Baseline Population']=10312

rm2=pd.merge(rmerge,pstore)

rm2.loc[:,'ndays']=rm2['Reporting Month'].apply(lambda t: pd.Period(t, freq='S').days_in_month)
rm2.loc[:,'Current GPCD']=rm2['Current']/(rm2['ndays']*rm2['Total Population Served'])
rm2.loc[:,'Baseline GPCD']=rm2['Baseline']/(rm2['ndays']*rm2['Baseline Population'])

In [56]:
rm2

,Supplier Name,Reporting Month,Total Population Served,Hydrologic Region,Current,Month,Baseline,Baseline Population,ndays,Current GPCD,Baseline GPCD
0,East Bay Municipal Utilities District,2023-02-15,1440000,San Francisco Bay,3.358000e+09,2,4.084900e+09,1405000.0,28,83.283730,103.835791
1,East Bay Municipal Utilities District,2022-02-15,1430000,San Francisco Bay,3.898000e+09,2,4.084900e+09,1405000.0,28,97.352647,103.835791
2,East Bay Municipal Utilities District,2023-01-15,1440000,San Francisco Bay,3.696000e+09,1,3.827100e+09,1405000.0,31,82.795699,87.868213
3,East Bay Municipal Utilities District,2022-01-15,1420000,San Francisco Bay,3.807000e+09,1,3.827100e+09,1405000.0,31,86.483417,87.868213
4,East Bay Municipal Utilities District,2022-12-15,1430000,San Francisco Bay,3.722000e+09,12,4.187100e+09,1405000.0,31,83.961200,96.133624
...,...,...,...,...,...,...,...,...,...,...,...
8070,Santa Clarita Valley Water Agency,2021-07-15,286868,South Coast,2.547461e+09,7,2.413565e+09,280100.0,31,286.459812,277.961238
8071,Santa Clarita Valley Water Agency,2022-06-15,295639,South Coast,1.999796e+09,6,2.170891e+09,280100.0,30,225.477295,258.347095
8072,Santa Clarita Valley Water Agency,2022-05-15,295639,South Coast,1.965563e+09,5,2.052642e+09,280100.0,31,214.468469,236.395114
8073,Santa Clarita Valley Water Agency,2022-04-15,295639,South Coast,1.641175e+09,4,1.113245e+09,280100.0,30,185.042640,132.481891
8074,Santa Clarita Valley Water Agency,2022-03-15,295639,South Coast,1.505946e+09,3,9.632755e+08,280100.0,31,164.318369,110.936817

In [91]:
group2 = rm2.groupby(
    ["Supplier Name", "Hydrologic Region"]
)[
    ["Current","Baseline","Total Population Served","ndays"]
].agg({
    "Current":"sum","Baseline":"sum","Total Population Served":"median","ndays":"sum"
}).reset_index()

In [93]:
group2['gallons saved'] = ((group2['Current']-group2['Baseline'])/group2["Total Population Served"])/group2["ndays"]

In [94]:
group2.sort_values("gallons saved")

,Supplier Name,Hydrologic Region,Current,Baseline,Total Population Served,ndays,gallons saved
392,Vernon City of,South Coast,3.346040e+09,3.701434e+09,112.0,608,-5219.015755
172,Humboldt Bay Municipal Water District,North Coast,9.551000e+07,1.504070e+08,602.0,580,-157.225914
21,Bella Vista Water District,Sacramento River,2.989683e+09,4.347836e+09,19150.0,577,-122.914744
202,Livingston City of,San Joaquin River,3.682207e+09,4.623882e+09,15052.0,608,-102.897128
269,"Perris, City of",South Coast,7.893480e+08,1.178757e+09,9000.0,549,-78.811776
...,...,...,...,...,...,...,...
184,"Kingsburg, City of",Tulare Lake,1.716940e+09,1.670046e+09,12338.0,608,6.251280
112,El Centro City of,Colorado River,4.470845e+09,4.116148e+09,46364.0,608,12.582677
196,Lee Lake Water District,South Coast,1.841145e+09,1.655849e+09,22485.0,580,14.208381
263,Paradise Irrigation District,Sacramento River,2.218100e+09,2.084610e+09,6000.0,608,36.592654
115,El Segundo City of,South Coast,3.802735e+09,3.006804e+09,16654.0,608,78.605542

In [95]:
def regional_calcs(df, current, baseline, pop):
    # val = df[rgpcd]
    # wt = df[pop]
    # wt_avg = (val * wt).sum() / wt.sum()
    # #return (val * wt).sum() / wt.sum()
    # total_gals = df[gals].sum()
    # total_pop = df[pop].sum()
    # return pd.Series([total_pop, total_gals, wt_avg], index=['total_pop', 'total_gallons', 'pop_weighted_rgpcd'])
    return ( (df[current] - df[baseline]) * df[pop]).sum() /df[pop].sum()

In [96]:
regional = rm2.groupby(
    ['Hydrologic Region']
).apply(
    regional_calcs,
    "Current GPCD",
    "Baseline GPCD",
    "Total Population Served" 
).reset_index()

In [97]:
regional

   Hydrologic Region          0
0      Central Coast  -6.337260
1     Colorado River  -0.405014
2        North Coast -16.280608
3     North Lahontan -13.618778
4   Sacramento River -22.016257
5  San Francisco Bay -14.164930
6  San Joaquin River -11.921389
7        South Coast  -7.407365
8     South Lahontan -12.372918
9        Tulare Lake -10.878103

In [98]:
((rm2['Current GPCD']-rm2['Baseline GPCD'])*rm2['Total Population Served']).sum()/rm2['Total Population Served'].sum()

-10.205117662421753

In [99]:
group = rm2.groupby("Supplier Name")[["Current GPCD", "Baseline GPCD"]].mean().reset_index()

In [100]:
group['diff'] = group['Current GPCD']-group['Baseline GPCD']

In [101]:
group.sort_values("diff")

,Supplier Name,Current GPCD,Baseline GPCD,diff
392,Vernon City of,49106.799961,54381.510401,-5274.710440
263,Paradise Irrigation District,641.205997,1139.128162,-497.922165
172,Humboldt Bay Municipal Water District,262.061665,432.503709,-170.442043
21,Bella Vista Water District,269.967212,389.563161,-119.595949
202,Livingston City of,402.102199,513.182677,-111.080478
...,...,...,...,...
14,Atascadero Mutual Water Company,141.602378,130.368529,11.233848
112,El Centro City of,161.205708,145.720398,15.485310
83,Coachella Valley Water District,319.132577,301.404808,17.727769
189,Lake Arrowhead Community Services District,64.537900,41.255686,23.282214
115,El Segundo City of,372.123314,297.268665,74.854649

In [25]:
#What's the best way to fill in missing values?
#Method 1: fill in with prior year data
#Pro: uses agency's own reported values for a given month
#Con: may not be accurate representation of "current" use (restrictions, weather, population changes, etc)

dcopy=reported.pivot_table(index='Reporting Month',columns='Supplier Name',values='CALCULATED Total Potable Water Production Gallons (Ag Excluded)')
dcopy2=dcopy.copy()
dcopy2.loc[:,'Month_Reporting']=dcopy.index.month
dcopy2.loc[:,'Year_Reporting']=dcopy.index.year
for i,r in dcopy2.iterrows():
    #each row is a unique month/year
    r_miss=r[r.isna()].index
    rm=r['Month_Reporting']
    ry=r['Year_Reporting']
    for s in r_miss:
        dsub=dcopy2[dcopy2['Month_Reporting']==rm]
        dsub2=dsub[[s,'Year_Reporting']].dropna(subset=[s])
        dsub2.loc[:,'Year_minus']=(dsub2['Year_Reporting']-ry).abs()
        nearest_vals=dsub2[dsub2['Year_minus']==dsub2['Year_minus'].min()]
        if (len(nearest_vals)>1):
            #Choose the one with the lower value
            choose_val=nearest_vals[nearest_vals['Year_Reporting']==nearest_vals['Year_Reporting'].min()]
            dcopy.loc[i,s]=choose_val[s].values[0]
        else:
            dcopy.loc[i,s]=nearest_vals[s].values[0]

#Table with reporting month as column and supplier as row                    
df_estimate_prod=dcopy.transpose()
df_reported_prod=reported.pivot_table(index='Supplier Name',columns='Reporting Month',values='CALCULATED Total Potable Water Production Gallons (Ag Excluded)')
#Table in long form 
estimated_prod=df_estimate_prod.reset_index().melt(id_vars='Supplier Name',value_name='Estimated Prod minus Ag')
reported_prod=df_reported_prod.reset_index().melt(id_vars='Supplier Name',value_name='Reported Prod minus Ag')
#Merge 2 long tables to get side by side comparison
prod_rep_est=pd.merge(estimated_prod,reported_prod)

In [41]:
len(prod_rep_est[ 
    ( prod_rep_est['Reported Prod minus Ag'].isna() ) &
    ( prod_rep_est['Reporting Month']>pd.to_datetime('2021-07-01',format="%Y-%m-%d") )
])

149

In [42]:
149/8220

0.018126520681265208

In [75]:
#Limit the dataset to the months we're interested in 
prod_rep_sub=prod_rep_est[prod_rep_est['Reporting Month']>pd.to_datetime('2021-07-01',format="%Y-%m-%d")]
prod_rep_sub.loc[:,'Month']=prod_rep_sub['Reporting Month'].dt.month
#merge the baseline
mpr=pd.merge(prod_rep_sub,baseline[['Supplier Name','Month','Total Potable Production minus ag, gallons']].rename(columns={'Total Potable Production minus ag, gallons':'Baseline'}))
baseline_sum_1=mpr['Baseline'].sum()
current_sum_1=mpr['Estimated Prod minus Ag'].sum()
diff_sum_1=baseline_sum-current_sum
print('Baseline Gallons (AF)',baseline_sum_1/325851,'Current Gallons (AF)',current_sum_1/325851,'Diff (AF)',diff_sum_1/325851)

Baseline Gallons (AF) 9645008.23805014 Current Gallons (AF) 9011468.832968567 Diff (AF) 633539.4050815752
8220

In [92]:
#Method 2: Apply the percent decrease for the hydrologic region to the baseline 
#Pro: Uses regional trend to approximate change in water use, rather than relying on past values which might not reflect current conditions
#Con: might not reflect what's going on at the individual agency level. 

#Limit the dataset to the months we're interested in 
reported_drought=reported[reported['Reporting Month']>pd.to_datetime('2021-07-01',format='%Y-%m-%d')]
rsub=reported_drought[['Supplier Name','Reporting Month','Hydrologic Region','CALCULATED Total Potable Water Production Gallons (Ag Excluded)']]
rsub.loc[:,'Month']=rsub['Reporting Month'].dt.month
#Merge the baseline with the current data
merged_data=pd.merge(rsub.rename(columns={'CALCULATED Total Potable Water Production Gallons (Ag Excluded)':'Current'}),
baseline[['Supplier Name','Month','Total Potable Production minus ag, gallons']].rename(columns={'Total Potable Production minus ag, gallons':'Baseline'}))

htab=pd.DataFrame()
x=0
for h in sorted(merged_data['Hydrologic Region'].unique()):
    hsub=merged_data[merged_data['Hydrologic Region']==h]
    for d in sorted(hsub['Reporting Month'].unique()):
        dsub=hsub[hsub['Reporting Month']==d]
        bsum=dsub['Baseline'].sum()
        csum=dsub['Current'].sum()
        pct_change=(csum-bsum)/bsum
        htab.loc[x,'Hydrologic Region']=h
        htab.loc[x,'Reporting Month']=d
        htab.loc[x,'Month']=pd.to_datetime(d).month
        htab.loc[x,'Hydro Pct diff']=pct_change

        x+=1

#Build table with all supplier names and dates, then apply percentages as necessary
datetab=pd.DataFrame({'Reporting Month':reported_drought['Reporting Month'].unique()})
ndates=len(reported_drought['Reporting Month'].unique())

full_dat=pd.DataFrame()
for s in merged_data['Supplier Name'].unique():
    ssub=merged_data[merged_data['Supplier Name']==s].drop_duplicates()

    if len(ssub)<ndates:
        #Merge with datetab, dropping baseline
        smerge=pd.merge(datetab,ssub,how='left').drop('Baseline',axis=1)
        smerge.loc[:,'Supplier Name']=ssub['Supplier Name'].unique()[0]
        smerge.loc[:,'Hydrologic Region']=ssub['Hydrologic Region'].unique()[0]
        smerge.loc[:,'Month']=smerge['Reporting Month'].dt.month
        #re-merge baseline
        smerge=pd.merge(smerge,baseline[['Supplier Name','Month','Total Potable Production minus ag, gallons']].rename(columns={'Total Potable Production minus ag, gallons':'Baseline'}))
        #merge the pct change
        s2=pd.merge(smerge,htab)
        s2.loc[s2['Current'].isna(),'Current']=s2.loc[s2['Current'].isna(),'Baseline']*(1+s2.loc[s2['Current'].isna(),'Hydro Pct diff'])
        full_dat=full_dat.append(s2)
    else:
        full_dat=full_dat.append(ssub)

In [93]:
baseline_sum_2=full_dat['Baseline'].sum()
current_sum_2=full_dat['Current'].sum()
diff_sum_2=baseline_sum_2-current_sum_2     
print('Baseline Gallons (AF)',baseline_sum_2/325851,'Current Gallons (AF)',current_sum_2/325851,'Diff (AF)',diff_sum_2/325851)

Baseline Gallons (AF) 9645008.238050139 Current Gallons (AF) 9005233.069945347 Diff (AF) 639775.1681047925